spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local
    include:
      - aws
      - oauth
      - openai
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: ${SECRET_KEY:your-secret-key-should-be-at-least-32-characters-long}
  accessToken:
    expiration: ${EXPIRATION_TIME:86400000}
  refreshToken:
    expiration: ${REFRESH_EXPIRATION_TIME:1209600000}
  issuer: ${ISSUER:inpeak}
  redirectUri: ${REDIRECT_URL:http://localhost:5173}

server:
  tomcat:
    max-http-form-post-size: 50MB

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/inpeak-db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:inpeak-db
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
