version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/inpeak-back/inpeak
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
