version: 0.0
os: linux

files:
  - source: /
    destination: /opt/inpeak
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /opt/inpeak
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /opt/inpeak/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /opt/inpeak/inpeak-backend.jar
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: ec2-user
